rewards:
  vip:
    currency:
      - "money@50000000"
      - "coins@500000"
    items:
      - "vip_ring@1"
      - "vip_title@1"
      - "vip_medal@1"
      - "trumpet_vip@30"
      - "stone_realm@10"
  svp:
    currency:
      - "money@100000000"
      - "coins@1000000"
    items:
      - "svp_ring@1"
      - "svp_title@1"
      - "svp_medal@1"
      - "trumpet_vip@30"
      - "stone_realm@30"
  mvp:
    currency:
      - "money@500000000"
      - "coins@3000000"
    items:
      - "mvp_ring@1"
      - "mvp_title@1"
      - "mvp_medal@1"
      - "trumpet_mvp@30"
      - "stone_realm@100"